name: gwent_go
description: "A cross-platform Flutter implementation of the card game Gwent."
publish_to: 'none'

version: 0.1.0+1

environment:
  sdk: ^3.13.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any

  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.5
  audioplayers: ^6.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/audio/
    - assets/cards/
    - assets/icons/
    - assets/factions/
